services:

  mongodb:
    image: mongo:8.2-rc-noble
    ports:
      - '27017:27017'
    volumes:
      - ./volumes/dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: examples

volumes:
  dbdata:

# networks:
#   node-network:
#     driver: bridge
